import './globals.css'
import { Inter } from 'next/font/google'
import Button from './components/Button'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Uniti by PotatoPotata',
  description: 'Generated by create next app',
}

var walletAddress = true; //TEMP

export default function RootLayout({ children }) {
  if (!walletAddress) {
    return (
      <html lang="en">
        <body className={inter.className}>
          <img src="../public/potatopotata.png" alt="" />
          <h1>Uniti</h1>
          <Button text="Connect Wallet" />
          {children}
        </body>
      </html>
    )
  }
  else if (walletAddress) {
    return (
      <html lang="en">
        <body className={inter.className}>
          <img src="../public/potatopotata.png" alt="" />
          <h1>Uniti</h1>
          {/* <h4>{walletAddress.value}</h4> */}
          {children}
        </body>
      </html>
    )
  }
}

